parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: dm
        connections:
            dm:
                dbname: '%env(DATABASE_DM_DB)%'
                host: '%env(DATABASE_DM_HOST)%'
                port: '%env(DATABASE_DM_PORT)%'
                user: '%env(DATABASE_DM_USER)%'
                password: '%env(DATABASE_DM_PASS)%'
                driver: 'pdo_mysql'
                server_version: 'mariadb-10.2.16'
                charset: utf8mb4
                mapping_types:
                    enum: string
            coa:
                dbname: '%env(DATABASE_COA_DB)%'
                host: '%env(DATABASE_COA_HOST)%'
                port: '%env(DATABASE_COA_PORT)%'
                user: '%env(DATABASE_COA_USER)%'
                password: '%env(DATABASE_COA_PASS)%'
                driver: 'pdo_mysql'
                server_version: 'mariadb-10.2.16'
                charset: utf8mb4
                schema_filter: (inducks_countryname|inducks_entry|inducks_entryurl|inducks_issue|inducks_person|inducks_publication|inducks_story|inducks_storyversion)
                mapping_types:
                    enum: string
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: 'dm'
        entity_managers:
            dm:
                connection: dm
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Dm'
                        prefix: 'App\Models\Dm'
                        alias: Dm
            coa:
                connection: coa
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Coa'
                        prefix: 'App\Models\Coa'
                        alias: Coa
