security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_user_provider:
            memory:
                users:
                    ducksmanager:  { password: '%env(ROLE_PASSWORD_DUCKSMANAGER)%', roles: [ 'ROLE_COLLECTION' ] }
                    whattheduck: { password: '%env(ROLE_PASSWORD_WHATTHEDUCK)%', roles: [ 'ROLE_COLLECTION' ] }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            http_basic: true

    access_control:
        - { path: ^/rawsql, roles: ROLE_RAWSQL }
        - { path: ^/ducksmanager/resetDemo, roles: ROLE_RESETDEMO }
        - { path: ^/collection/, roles: ROLE_COLLECTION }
        - { path: ^/edgecreator/, roles: ROLE_EDGECREATOR }
