version: '2.4'

x-gelf-logging: &gelf-logging
  logging:
    driver: gelf
    options:
      gelf-address: $LOG_SERVER_ADDRESS

services:
  web:
    container_name: dm-server-web
    image: "nginx:1.15"
    ports:
     - "8001:80"
    depends_on:
     - db_coa
     - db_cover_id
     - db_dm_copy
     - db_dm_stats
     - db_edgecreator
     - php
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
     - ./current:/var/www:z
    networks:
     - front-network
    << : *gelf-logging

  php:
    container_name: dm-server-php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - ./ssmtp.conf:/etc/ssmtp/ssmtp.conf
     - ./current:/var/www:z
    environment:
      DM_SERVER_ADDRESS: "$DM_SERVER_HOST:$DM_SERVER_PORT"
    networks:
     - front-network
     - db-network
     - cover-id-network
    << : *gelf-logging

  coa-updater:
    container_name: coa-updater
    image: "bperel/coa-updater"
    depends_on:
     - db_coa
    environment:
      - MYSQL_HOST=db_coa
      - MYSQL_DATABASE=coa
      - MYSQL_PASSWORD=$MYSQL_ROOT_PASSWORD
    networks:
     - db-network
    << : *gelf-logging
  db_coa:
    container_name: mariadb-server-for-coa-box
    image: "mariadb:10.2"
    volumes:
     - $MYSQL_INIT_SCRIPT_COA:/docker-entrypoint-initdb.d/$MYSQL_INIT_SCRIPT_TARGET_FILE_NAME:ro
    ports:
     - "44000:3306"
    environment:
      MYSQL_DATABASE: coa
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    networks:
     - db-network
     - cover-id-network
    << : *gelf-logging

  cover-updater:
    container_name: cover-updater
    image: "bperel/duck-cover-id-updater"
    depends_on:
     - db_cover_id
     - db_coa
    environment:
      - MYSQL_COVER_INFO_HOST=db_cover_id
      - MYSQL_COVER_INFO_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_COVER_INFO_DATABASE=cover_info
      - MYSQL_COA_HOST=db_coa
      - MYSQL_COA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_COA_DATABASE=coa
      - PASTEC_HOST=pastec
      - PASTEC_PORT=4212
      - PASTEC_CONTAINER_HOME=/pastec/build
    networks:
     - db-network
     - cover-id-network
    << : *gelf-logging
  db_cover_id:
    container_name: mariadb-server-for-cover-info-box
    image: "mariadb:10.2"
    volumes:
     - $MYSQL_INIT_SCRIPT_COVER_INFO:/docker-entrypoint-initdb.d/$MYSQL_INIT_SCRIPT_TARGET_FILE_NAME:ro
    ports:
     - "44009:3306"
    environment:
      MYSQL_DATABASE: cover_info
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
     - db-network
    << : *gelf-logging
  pastec:
    container_name: pastec-ubuntu-1704-timestamps
    image: "bperel/pastec-ubuntu-1704-timestamps"
    volumes:
     - $PASTEC_INIT_INDEX:/pastec-index-last.dat:ro
    command: "./pastec -p 4212 -i /pastec-index-last.dat /pastec/data/visualWordsORB.dat"
    networks:
     - cover-id-network

  db_dm_copy:
    container_name: mariadb-server-for-dm
    image: "mariadb:10.2"
    volumes:
     - $MYSQL_INIT_SCRIPT_DM:/docker-entrypoint-initdb.d/$MYSQL_INIT_SCRIPT_TARGET_FILE_NAME:ro
    ports:
     - "44002:3306"
    environment:
      MYSQL_DATABASE: dm
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
     - db-network
    << : *gelf-logging
  db_edgecreator:
    container_name: mariadb-server-for-edgecreator
    image: "mariadb:10.2"
    volumes:
     - $MYSQL_INIT_SCRIPT_EDGECREATOR:/docker-entrypoint-initdb.d/$MYSQL_INIT_SCRIPT_TARGET_FILE_NAME:ro
    ports:
     - "44003:3306"
    environment:
      MYSQL_DATABASE: edgecreator
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
     - db-network
    << : *gelf-logging

  stats-updater:
    container_name: stats-updater
    image: "bperel/dm-stats-updater"
    depends_on:
    - db_coa
    - db_dm_stats
    - db_dm_copy
    environment:
    - MYSQL_COA_HOST=db_coa
    - MYSQL_COA_DATABASE=coa
    - MYSQL_DM_STATS_HOST=db_dm_stats
    - MYSQL_DM_STATS_DATABASE=dm_stats
    - MYSQL_DM_HOST=db_dm_copy
    - MYSQL_DM_DATABASE=dm
    - MYSQL_PASSWORD=$MYSQL_ROOT_PASSWORD
    networks:
    - db-network
    << : *gelf-logging
  db_dm_stats:
    container_name: mariadb-server-for-dm-stats
    image: "mariadb:10.2"
    volumes:
     - $MYSQL_INIT_SCRIPT_DM_STATS:/docker-entrypoint-initdb.d/$MYSQL_INIT_SCRIPT_TARGET_FILE_NAME:ro
    ports:
     - "44010:3306"
    environment:
      MYSQL_DATABASE: dm_stats
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
     - db-network
    << : *gelf-logging
  swagger:
    container_name: swagger
    image: "swaggerapi/swagger-ui"
    ports:
     - "8081:8080"
    depends_on:
     - web
     - php
    environment:
      API_URL: "http://$DM_SERVER_HOST:$DM_SERVER_PORT/status/swagger.json"
      SWAGGER_JSON: "http://$DM_SERVER_HOST:$DM_SERVER_PORT/status/swagger.json"
    networks:
     - front-network
    << : *gelf-logging

networks:
  front-network:
    driver: bridge
  db-network:
    driver: bridge
  cover-id-network:
    driver: bridge
