version: '2.4'
services:
  web:
    container_name: dm-server-flex-web
    image: "nginx:1.15"
    ports:
     - "10002:80"
    depends_on:
     - php
    restart: always
    volumes:
     - .:/var/www/html:z
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
     - front-network

  php:
    container_name: dm-server-flex-php
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
     - .:/var/www/html
     - ./php.xdebug.ini:/usr/local/etc/php/php.ini:z
    environment:
      DM_SERVER_ADDRESS: "$DM_SERVER_HOST:$DM_SERVER_PORT"
    networks:
     - front-network
     - db-network
    command: sh -c 'composer install --no-plugins --no-scripts && php-fpm'

networks:
  front-network:
    driver: bridge
  db-network:
    external:
      name: dmserver_db-network
