version: '2.1'
services:
  web:
    container_name: dm-server
    build: .
    ports:
     - "10001:80"
    depends_on:
     - db_coa
     - db_cover_id
     - db_dm
     - db_dm_stats
     - db_edgecreator
    volumes:
     - .:/var/www/html/dm-server
  db_coa:
    container_name: mariadb-server-for-coa-box
    image: "bperel/coa-box"
    extends:
      file: docker-compose-db-with-healthcheck.yml
      service: db-with-healthcheck
    ports:
     - "64000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: coa
  db_cover_id:
    container_name: mariadb-server-for-cover-info-box
    extends:
      file: docker-compose-db-with-healthcheck.yml
      service: db-with-healthcheck
    ports:
     - "64001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: cover_info
  db_dm:
    container_name: mariadb-server-for-dm
    extends:
      file: docker-compose-db-with-healthcheck.yml
      service: db-with-healthcheck
    ports:
     - "64002:3306"
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: dm
  db_edgecreator:
    container_name: mariadb-server-for-edgecreator
    extends:
      file: docker-compose-db-with-healthcheck.yml
      service: db-with-healthcheck
    ports:
     - "64003:3306"
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: edgecreator
  db_dm_stats:
    container_name: mariadb-server-for-dm-stats
    extends:
      file: docker-compose-db-with-healthcheck.yml
      service: db-with-healthcheck
    ports:
     - "64010:3306"
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: dm_stats
  pastec:
    container_name: pastec-ubuntu-1704-timestamps
    image: "bperel/pastec-ubuntu-1704-timestamps"
    ports:
     - "4212:4212"
    restart: always
networks:
  default:
    external:
      name: dm_network