version: '2.1'
services:
  web:
    container_name: dm-server
    build: .
    ports:
     - "8001:80"
    depends_on:
     - db_coa
     - db_cover_id
     - db_dm
     - db_dm_stats
     - db_edgecreator
  db_coa:
    container_name: mariadb-server-for-coa-box
    image: "bperel/coa-box"
    extends:
      file: docker-compose-db-with-healthcheck.yml
      service: db-with-healthcheck
    ports:
     - "44000:3306"
    volumes:
     - ../coa-box/scripts:/home/scripts
     - ../coa-box/container.properties:/home/container.properties
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: coa
  db_cover_id:
    container_name: mariadb-server-for-cover-info-box
    build:
      context: ../duck-cover-id
    ports:
     - "44009:3306"
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: cover_info
    volumes:
     - ../duck-cover-id/scripts:/home/scripts
     - ../duck-cover-id/container.properties:/home/container.properties
    healthcheck:
      test: grep 'Server socket created' /var/log/mysql/error.log
      interval: 2s
      timeout: 30s
    command: mysqld --log-error=/var/log/mysql/error.log
  db_dm:
    container_name: mariadb-server-for-dm
    extends:
      file: docker-compose-db-with-healthcheck.yml
      service: db-with-healthcheck
    ports:
     - "44002:3306"
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: dm
  db_edgecreator:
    container_name: mariadb-server-for-edgecreator
    extends:
      file: docker-compose-db-with-healthcheck.yml
      service: db-with-healthcheck
    ports:
     - "44003:3306"
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: edgecreator
  db_dm_stats:
    container_name: mariadb-server-for-dm-stats
    extends:
      file: docker-compose-db-with-healthcheck.yml
      service: db-with-healthcheck
    ports:
     - "44010:3306"
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: dm_stats
    volumes:
     - ../dm-stats/scripts:/home/scripts
     - ../dm-stats/container.properties:/home/container.properties
  pastec:
    container_name: pastec-ubuntu-1704-timestamps
    image: "bperel/pastec-ubuntu-1704-timestamps"
    ports:
     - "4214:4212"
    restart: always
networks:
  default:
    external:
      name: dm_network