version: '2.1'
services:
  web:
    container_name: dm-server
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
     - "10001:80"
    depends_on:
     - db_coa
     - db_cover_id
     - db_dm
     - db_dm_stats
     - db_edgecreator
    volumes:
     - .:/var/www/html/dm-server:z
     - ./php.xdebug.ini:/usr/local/etc/php/php.ini:z
  db_coa:
    container_name: db_coa
    image: "bperel/coa-box"
    ports:
     - "64000:3306"
    environment:
      MYSQL_DATABASE: coa
  db_cover_id:
    container_name: db_cover_id
    image: "mariadb:10.2"
    ports:
     - "64001:3306"
    environment:
      MYSQL_DATABASE: cover_info
  db_dm:
    container_name: db_dm
    image: "mariadb:10.2"
    ports:
     - "64002:3306"
    environment:
      MYSQL_DATABASE: dm
  db_edgecreator:
    container_name: db_edgecreator
    image: "mariadb:10.2"
    ports:
     - "64003:3306"
    environment:
      MYSQL_DATABASE: edgecreator
  db_dm_stats:
    container_name: db_dm_stats
    image: "mariadb:10.2"
    ports:
     - "64010:3306"
    environment:
      MYSQL_DATABASE: dm_stats
  pastec:
    container_name: pastec
    image: "bperel/pastec-ubuntu-1704-timestamps"
    ports:
     - "4212:4212"
  swagger:
    container_name: swagger
    image: "swaggerapi/swagger-ui"
    ports:
     - "8081:8080"
    environment:
      API_URL: http://localhost:10001/dm-server/status/swagger.json
      SWAGGER_JSON: http://dm-server/dm-server/status/swagger.json
networks:
  default:
    external:
      name: dm_network
