monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: info
            handler: nested
            excluded_http_codes: [404]
        nested:
            type: stream
            path: "php://stdout"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "php://stdout"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
